name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches-ignore:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile # optional, --immutable

      - name: Run Lint
        run: |
          yarn lint

      - name: Run Build
        run: |
          yarn build

      - name: Run Tests
        # Run *only* tests with an increased JS heap size limit
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: yarn test

      - name: Run Security Audit
        # Previously, `yarn audit --groups dependencies` was used, but now the appropriate
        # subcommand is `yarn npm audit`, with the `--groups` option replaced by `environment`.
        # See https://yarnpkg.com/cli/npm/audit for more.
        run: |
          yarn npm audit --environment production
